### ISSUE TITLE
Update Homepages Widget Guideline Document 

### ISSUE THREAD

**Issue by theakatz** [infor-design/website#584] opened 2018-06-19 19:45 UTC
With Workspaces coming soon to Homepages, I'd like H&L to specify the updated Widget Guidelines (that we currently serve as a PDF in the SDK, also attached) and host it on design.infor.com

The updated guideline would cover the UI design principles as used previously with the normal widgets.

> Frank: For the interim, I think hosting it on design.infor.com is great, but we do need the design guidelines updated to include Workspaces. We’ll be going live with supporting Workspaces in our SDK around December (and Fredrik can add more details as necessary), but we want to ensure that the guidelines from H&L are in place to govern the UI for all adopters.

STEPS:
- [x] get current guidelines onto site 
- [ ] Kelsey/Becca to update widget guidelines to include Workspaces --Fredrik Eriksson and Frank Zhang are contacts

**Comment by theakatz** [comment] 2018-06-19 19:46
[SoHo_Xi_Widget_Guideline_04182016.pdf](https://github.com/infor-design/website/files/2116681/SoHo_Xi_Widget_Guideline_04182016.pdf)

**Comment by theakatz** [comment] 2018-06-20 14:47
dupe of #infor_design-system_160

**Comment by nickwynja** [comment] 2018-11-14 20:10
Still a duplicate of infor-design/design-system#160

**Closed by nickwynja** 2018-11-14 20:10 UTC
